"""empty message

Revision ID: 495569071a8b
Revises: 93548b44a291
Create Date: 2025-02-22 11:46:31.922172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495569071a8b'
down_revision = '93548b44a291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('street')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
