"""empty message

Revision ID: 9c7d94cc69b1
Revises: ffee160396fa
Create Date: 2025-02-20 18:56:11.482425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7d94cc69b1'
down_revision = 'ffee160396fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_brand_key', type_='unique')
        batch_op.drop_constraint('vehicles_model_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_unique_constraint('vehicles_model_key', ['model'])
        batch_op.create_unique_constraint('vehicles_brand_key', ['brand'])

    # ### end Alembic commands ###
